-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('Subgame_pb')


local localTable = {}
XTHH_RULES = protobuf.Descriptor()
localTable.XTHH_RULES_PIAO_PRIZE_FIELD = protobuf.FieldDescriptor()
localTable.XTHH_RULES_HU_LAIZINUM_FIELD = protobuf.FieldDescriptor()
localTable.XTHH_RULES_FENGDING_FIELD = protobuf.FieldDescriptor()


localTable.XTHH_RULES_PIAO_PRIZE_FIELD.name = "piao_prize"
localTable.XTHH_RULES_PIAO_PRIZE_FIELD.full_name = "XTHH_RULES.piao_prize"
localTable.XTHH_RULES_PIAO_PRIZE_FIELD.number = 1
localTable.XTHH_RULES_PIAO_PRIZE_FIELD.index = 0
localTable.XTHH_RULES_PIAO_PRIZE_FIELD.label = 1
localTable.XTHH_RULES_PIAO_PRIZE_FIELD.has_default_value = false
localTable.XTHH_RULES_PIAO_PRIZE_FIELD.default_value = 0
localTable.XTHH_RULES_PIAO_PRIZE_FIELD.type = 5
localTable.XTHH_RULES_PIAO_PRIZE_FIELD.cpp_type = 1

localTable.XTHH_RULES_HU_LAIZINUM_FIELD.name = "hu_laizinum"
localTable.XTHH_RULES_HU_LAIZINUM_FIELD.full_name = "XTHH_RULES.hu_laizinum"
localTable.XTHH_RULES_HU_LAIZINUM_FIELD.number = 2
localTable.XTHH_RULES_HU_LAIZINUM_FIELD.index = 1
localTable.XTHH_RULES_HU_LAIZINUM_FIELD.label = 1
localTable.XTHH_RULES_HU_LAIZINUM_FIELD.has_default_value = false
localTable.XTHH_RULES_HU_LAIZINUM_FIELD.default_value = 0
localTable.XTHH_RULES_HU_LAIZINUM_FIELD.type = 5
localTable.XTHH_RULES_HU_LAIZINUM_FIELD.cpp_type = 1

localTable.XTHH_RULES_FENGDING_FIELD.name = "fengding"
localTable.XTHH_RULES_FENGDING_FIELD.full_name = "XTHH_RULES.fengding"
localTable.XTHH_RULES_FENGDING_FIELD.number = 3
localTable.XTHH_RULES_FENGDING_FIELD.index = 2
localTable.XTHH_RULES_FENGDING_FIELD.label = 1
localTable.XTHH_RULES_FENGDING_FIELD.has_default_value = false
localTable.XTHH_RULES_FENGDING_FIELD.default_value = 0
localTable.XTHH_RULES_FENGDING_FIELD.type = 5
localTable.XTHH_RULES_FENGDING_FIELD.cpp_type = 1

XTHH_RULES.name = "XTHH_RULES"
XTHH_RULES.full_name = "XTHH_RULES"
XTHH_RULES.nested_types = {}
XTHH_RULES.enum_types = {}
XTHH_RULES.fields = {localTable.XTHH_RULES_PIAO_PRIZE_FIELD, localTable.XTHH_RULES_HU_LAIZINUM_FIELD, localTable.XTHH_RULES_FENGDING_FIELD}
XTHH_RULES.is_extendable = false
XTHH_RULES.extensions = {}

XTHH_RULES = protobuf.Message(XTHH_RULES)

